[package]
name = "battery_checker"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.37", features = ["derive"] }
cmd_lib = "1.9.5"
regex = "1.11.0"
